/**
 * element-plus component list
 */
export const components = [
  'ElButton',
  'ElContainer',
  'ElHeader',
  'ElMain',
  'ElAside',
  'ElFooter',
  'ElIcon',
  'ElRow',
  'ElCol',
  'ElLink',
  'ElScrollbar',
  'ElSpace',
  'ElConfigProvider',
  'ElAutocomplete',
  'ElCascader',
  'ElCheckbox',
  'ElCheckboxGroup',
  'ElColorPicker',
  'ElDatePicker',
  'ElForm',
  'ElFormItem',
  'ElInput',
  'ElInputNumber',
  'ElRadio',
  'ElRadioButton',
  'ElRadioGroup',
  'ElRate',
  'ElSelect',
  'ElOption',
  'ElOptionGroup',
  'ElSelectV2',
  'ElSlider',
  'ElSwitch',
  'ElTimePicker',
  'ElTimeSelect',
  'ElTransfer',
  'ElUpload',
  'ElAvatar',
  'ElBadge',
  'ElCalendar',
  'ElCard',
  'ElCarousel',
  'ElCarouselItem',
  'ElCollapse',
  'ElCollapseItem',
  'ElDescriptions',
  'ElDescriptionsItem',
  'ElEmpty',
  'ElImage',
  'ElImageViewer',
  'ElPagination',
  'ElProgress',
  'ElResult',
  'ElSkeleton',
  'ElSkeletonItem',
  'ElTable',
  'ElTableColumn',
  'ElTableV2',
  'ElTag',
  'ElCheckTag',
  'ElTimeline',
  'ElTimelineItem',
  'ElTree',
  'ElTreeV2',
  'ElTreeSelect',
  'ElAffix',
  'ElBacktop',
  'ElBreadcrumb',
  'ElBreadcrumbItem',
  'ElDropdown',
  'ElDropdownMenu',
  'ElDropdownItem',
  'ElMenu',
  'ElMenuItem',
  'ElSubMenu',
  'ElMenuItemGroup',
  'ElPageHeader',
  'ElSteps',
  'ElStep',
  'ElTabs',
  'ElTabPane',
  'ElAlert',
  'ElDialog',
  'ElDrawer',
  'ElPopconfirm',
  'ElPopover',
  'ElTooltip',
  'ElDivider',
]

export const proComponents = [
  { dirname: 'pro-checkbox', name: 'ProCheckbox' },
  { dirname: 'pro-crud', name: 'ProCrud' },
  { dirname: 'pro-dialog', name: 'ProDialog' },
  { dirname: 'pro-form', name: 'ProForm' },
  { dirname: 'pro-radio', name: 'ProRadio' },
  { dirname: 'pro-table', name: 'ProTable' },
]
